// src/sandbox/plugins/interface.ts

/**
 * Represents the availability and requirements of a kernel security feature.
 */
export interface FeatureSupport {
    isAvailable: boolean;
    reason?: string; // e.g., "Kernel version too old", "Not a Linux environment"
}

/**
 * Represents a security event generated by a kernel plugin.
 */
export interface PolicyEvent {
    timestamp: number;
    pid: number;
    tid: number;
    category: 'fs' | 'net' | 'exec' | 'antiEscape';
    syscall: string;
    target: string; // File path, IP:port, or binary path
    decision: 'allow' | 'deny' | 'warn';
    ruleId?: string; // ID of the rule that was matched
    stack?: string; // Optional stack trace if available
}

/**
 * The common interface for all kernel-level security enforcement plugins.
 */
export interface SandboxPlugin {
    /**
     * The name of the plugin (e.g., "landlock", "seccomp").
     */
    name: string;

    /**
     * Detects if the required kernel feature is available on the host system.
     * @returns {FeatureSupport} An object indicating availability.
     */
    detect(): FeatureSupport;

    /**
     * Validates the relevant sections of the normalized policy.
     * Throws an error if the policy contains semantic errors for this plugin.
     * @param {any} policy - The normalized policy object.
     */
    validate(policy: any): void;

    /**
     * Applies the security policy using the kernel feature.
     * This may be called pre-fork or post-fork/pre-exec depending on the plugin.
     * @param {any} policy - The normalized policy object.
     * @param {number} targetPid - The PID of the process to apply the policy to (if applicable).
     */
    apply(policy: any, targetPid?: number): Promise<void>;

    /**
     * Returns an async iterator for streaming policy events from the kernel.
     * Not all plugins will generate events.
     * @returns {AsyncGenerator<PolicyEvent>} An async generator of policy events.
     */
    events?(): AsyncGenerator<PolicyEvent>;
}
