export const exampleCatalog = [
  {
    id: "hello_world",
    label: "Hello World",
    description: "Baseline output and environment info.",
    group: "Basics",
    file: "hello_world.py",
  },
  {
    id: "fs_allow_tmp",
    label: "FS Allow /tmp",
    description: "Allowed filesystem access under FS allowlist.",
    group: "Filesystem",
    file: "fs_allow_tmp.py",
  },
  {
    id: "fs_allow_etc",
    label: "FS Allow /etc",
    description: "Read /etc directory entries.",
    group: "Filesystem",
    file: "fs_allow_work.py",
  },
  {
    id: "fs_deny_etc",
    label: "FS Deny /etc/hosts",
    description: "Denied filesystem access outside allowlist.",
    group: "Filesystem",
    file: "fs_deny_etc.py",
  },
  {
    id: "fs_deny_etc_hostname",
    label: "FS Deny /etc/hostname",
    description: "Blocked read outside allowlist.",
    group: "Filesystem",
    file: "fs_deny_var_log.py",
  },
  {
    id: "net_rfc1918_block",
    label: "Net Deny RFC1918",
    description: "Blocked outbound access to private ranges.",
    group: "Network",
    file: "net_rfc1918_block.py",
  },
  {
    id: "net_allow_external",
    label: "Net Allow External",
    description: "Outbound HTTPS to public endpoint.",
    group: "Network",
    file: "net_allow_external.py",
  },
  {
    id: "net_warn_db_ports",
    label: "Net Warn DB Ports",
    description: "Connection attempt to DB ports.",
    group: "Network",
    file: "net_warn_db_ports.py",
  },
  {
    id: "net_warn_ssh",
    label: "Net Warn SSH",
    description: "Connection attempt to SSH port.",
    group: "Network",
    file: "net_warn_ssh.py",
  },
  {
    id: "net_warn_mysql",
    label: "Net Warn MySQL",
    description: "Connection attempt to MySQL port.",
    group: "Network",
    file: "net_warn_mysql.py",
  },
  {
    id: "exec_allow_python",
    label: "Exec Allow Python",
    description: "Allowed exec for Python interpreter.",
    group: "Execution",
    file: "exec_allow_python.py",
  },
  {
    id: "exec_deny_shell",
    label: "Exec Deny /bin/sh",
    description: "Denied exec for /bin/sh.",
    group: "Execution",
    file: "exec_deny_shell.py",
  },
  {
    id: "exec_deny_cat",
    label: "Exec Deny /bin/cat",
    description: "Denied exec for /bin/cat.",
    group: "Execution",
    file: "exec_deny_cat.py",
  },
  {
    id: "exec_deny_ls",
    label: "Exec Deny /bin/ls",
    description: "Denied exec for /bin/ls.",
    group: "Execution",
    file: "exec_deny_ls.py",
  },
  {
    id: "exec_deny_curl",
    label: "Exec Deny /usr/bin/curl",
    description: "Denied exec for curl.",
    group: "Execution",
    file: "exec_deny_curl.py",
  },
  {
    id: "exec_deny_bun",
    label: "Exec Deny bun",
    description: "Denied exec for bun.",
    group: "Execution",
    file: "exec_deny_bun.py",
  },
  {
    id: "exec_deny_bash",
    label: "Exec Deny /bin/bash",
    description: "Denied exec for /bin/bash.",
    group: "Execution",
    file: "exec_deny_bash.py",
  },
];
